#
name: Test

on: [ push ]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.go-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [ Ubuntu, macOS ]
        go-version: [ '1.22' ]
        include:
          - os: Ubuntu
            image: ubuntu-22.04
          - os: macOS
            image: macos-12
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Show Go version
        run: go version
      - name: Install dependencies
        run: |
          go get ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      - name: Test
        run: go test -v ./...
      - name: Generate coverage report
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
#
